# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: studiofonkel.nl
description: Studio Fonkel
author:
  name: Studio Fonkel
  email: info@studiofonkel.nl

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: pygments

collections:
  cases:
    output: true
    permalink: /cases/:path/
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"


picture:
  source: "img/_source"
  output: "generated"
  markup: "picture"
  presets:
    teamwidget_member:
      ppi: [1, 1.5, 2]
      attr:
        class: "teamwidget-member-icon"
        itemprop: "image"
      source_default:
        width: "300"
        height: "300"
    header:
      ppi: [1]
      attr:
        class: "header"
        itemprop: "image"
      source_medium:
        media: "(min-width: 36em)"
        width: "1200"
        height: "300"
      source_small:
        media: "(min-width: 18.5em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"
        height: "300"
    convince:
      ppi: [1, 1.5, 2]
      attr:
        class: "convince"
        itemprop: "image"
      source_default:
        width: "600"
        height: "300"
